Code refactoring. cb-include.cfg is now searched in PATH instead of dangerous $0 trickery

diff --git a/cb-compositor b/cb-compositor
--- a/cb-compositor
+++ b/cb-compositor
@@ -4,6 +4,10 @@
 # Written for CrunchBang Linux <http://crunchbang.org/>
 # by Philip Newborough <corenominal@corenominal.org>
 
+if ! . cb-include.cfg &> /dev/null; then
+    echo '  Failed to locate cb-include.cfg in PATH' >&2
+    exit 1
+fi
 
 # ------------- Set xcompmgr command options -----------------------------------
 if glxinfo | egrep -iq 'direct rendering: yes'; then
@@ -14,13 +18,13 @@ fi
 
 # Edit xcompmgr settings
 if [[ $1 = '--edit' ]]; then
-    if [[ ! -f /home/$USER/.config/compton.conf ]]; then
-        cp '/etc/xdg/compton.conf' "/home/$USER/.config/compton.conf"
+    if [[ ! -f ~/.config/compton.conf ]]; then
+        cp '/etc/xdg/compton.conf' ~/.config/compton.conf
     fi
     if [[ -x /usr/bin/geany ]]; then
-        geany "/home/$USER/.config/compton.conf" &
+        geany ~/.config/compton.conf &
     else
-        terminator --command="nano /home/$USER/.config/compton.conf"
+        terminator --command='nano ~/.config/compton.conf'
     fi
     exit 0
 fi
@@ -28,9 +32,9 @@ fi
 # Toggle compositing with compton. Called with "cb-compositor --toggle"
 if [[ $1 = '--toggle' || $1 = '--start' ]]; then 
     if ! pidof compton > /dev/null; then
-      $EXECXCOMP &
+        $EXECXCOMP &
     else
-      killall compton
+        killall compton
     fi
     exit 0
 fi
@@ -42,7 +46,7 @@ if [[ $1 = '--restart' ]]; then
 fi
 
 if [[ $1 = '--watch' ]]; then
-    while inotifywait -e modify "/home/$USER/.config/compton.conf"; do
+    while inotifywait -e modify ~/.config/compton.conf; do
         cb-compositor --restart
     done
     exit 0
diff --git a/cb-dropbox-pipemenu b/cb-dropbox-pipemenu
--- a/cb-dropbox-pipemenu
+++ b/cb-dropbox-pipemenu
@@ -1,12 +1,19 @@
-#!/bin/sh
+#!/bin/bash
 # --------------------------------------------------------------------
 # An Openbox pipemenu for use with Dropbox and CrunchBang Linux.
 # Written for CrunchBang Linux <http://crunchbanglinux.org/>
 # by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
 # --------------------------------------------------------------------
+
+if ! . cb-include.cfg &> /dev/null; then
+    echo '  Failed to locate cb-include.cfg in PATH' >&2
+    exit 1
+fi
+
 # Set some variables
-USERDBDIR="/home/${USER}/.dropbox-dist"
-TMPFILE="/tmp/${USERNAME}_cbdropbox"
+USERDBDIR=~/.dropbox-dist/
+TMPFILE="/tmp/${USER}_cbdropbox/"
+
 # --------------------------------------------------------------------
 # manipulation
 # --------------------------------------------------------------------
@@ -24,54 +31,43 @@ fi
 if [[ $1 = '--install-dropbox' ]]; then
     zenity --question --title='Dropbox Installation' --text 'This script will install Dropbox.\nDo you want to proceed?' || exit 0
 
-    cd "/home/$USER"
+    cd ~
     
     platform=$(uname -m)
     platform=${platform,,}
     case $platform in
     "x86_64")
-        #DROPBOXURL="http://packages.crunchbang.org/waldorf-files/dropbox/64/dropbox.tar.gz"
-        DROPBOXURL="http://www.dropbox.com/download?plat=lnx.x86_64"
+        #DROPBOXURL='http://packages.crunchbang.org/waldorf-files/dropbox/64/dropbox.tar.gz'
+        DROPBOXURL='http://www.dropbox.com/download?plat=lnx.x86_64'
         ;;
     *)
-        #DROPBOXURL="http://packages.crunchbang.org/waldorf-files/dropbox/32/dropbox.tar.gz"
-        DROPBOXURL="http://www.dropbox.com/download?plat=lnx.x86"
+        #DROPBOXURL='http://packages.crunchbang.org/waldorf-files/dropbox/32/dropbox.tar.gz'
+        DROPBOXURL='http://www.dropbox.com/download?plat=lnx.x86'
         ;;
     esac
     
     curl -s -I "$DROPBOXURL" > "$TMPFILE"
 	if [[ $? = 0 ]]; then
-		
-		RESPONSE=$(head -n 1 $TMPFILE | awk '{ print $2 }')
+		read _ RESPONSE _ <<< $(head -n 1 "$TMPFILE")
 		
 		#if [ $RESPONSE -ne "200" ]; then
 		if [[ RESPONSE != 302 ]]; then
 			zenity --warning --title='Dropbox Installation' --text 'Error, failed to contact server. Please try again later.'
 			exit 1
 		else
-			wget "$DROPBOXURL" 2>&1 | \
+			wget "$DROPBOXURL" -O ~/dropbox.tar.gz 2>&1 | \
              sed -u 's/^.* \+\([0-9]\+%\) \+\([0-9.]\+[GMKB]\) \+\([0-9hms.]\+\).*$/\1\n# Downloading... \2 (\3)/' | \
              zenity --progress --title='Installing Dropbox' --auto-kill --auto-close
 		fi
-
 	else
         zenity --warning --title='Dropbox Installation' --text 'Error, failed to contact server. Please try again later.'
 		exit 1
 	fi
-	
-	#rename binary
-	if [[ -f /home/$USER/download?plat=lnx.x86_64 ]]; then
-		mv /home/$USER/download?plat=lnx.x86_64 /home/$USER/dropbox.tar.gz
-	fi
-	if [[ -f /home/$USER/download?plat=lnx.x86 ]]; then
-		mv /home/$USER/download?plat=lnx.x86 /home/$USER/dropbox.tar.gz
-	fi
-    sleep 1s
 
     #extract binary
-    tar -xf dropbox.tar.gz
+    tar -xf 'dropbox.tar.gz'
     #delete binary
-    rm dropbox.tar.gz
+    rm 'dropbox.tar.gz'
     
     #quick sanity check
     if [[ ! -x $USERDBDIR/dropboxd ]]; then
@@ -81,19 +77,19 @@ if [[ $1 = '--install-dropbox' ]]; then
     zenity --info --title='Dropbox Installation' --text "Dropbox has been installed to:\n$USERDBDIR"
     zenity --question --title='Dropbox Installation' --text 'Dropbox can be started automatically when you start your session. Would you like to autostart Dropbox when you login?'
     if [[ $? != 1 ]]; then
-        ans=$(zenity  --title="Dropbox Installation" --list  --text "It is a good idea to add a delay before autostarting Dropbox\nso that your system can establish a working network connection.\n\nSelect the number of seconds to delay Dropbox autostarting.\nClick \"Cancel\" if you do not want to add a delay." \
-        --radiolist  --column "Pick" --column "Seconds:" FALSE 10 FALSE 20 FALSE 30 FALSE 40 FALSE 50 TRUE 60);
+        ans=$(zenity  --title='Dropbox Installation' --list  --text 'It is a good idea to add a delay before autostarting Dropbox\nso that your system can establish a working network connection.\n\nSelect the number of seconds to delay Dropbox autostarting.\nClick "Cancel" if you do not want to add a delay.' \
+        --radiolist  --column 'Pick' --column 'Seconds:' FALSE 10 FALSE 20 FALSE 30 FALSE 40 FALSE 50 TRUE 60)
         if [[ $ans ]]; then
             echo "$ans"
-            echo "" >> "/home/$USER/.config/openbox/autostart"
-            echo "# Autostart the Dropbox deamon" >> "/home/$USER/.config/openbox/autostart"
-            echo "(sleep ${ans}s && ~/.dropbox-dist/dropboxd) &" >> "/home/$USER/.config/openbox/autostart"
-            echo "" >> "/home/$USER/.config/openbox/autostart"
+            echo >> ~/.config/openbox/autostart
+            echo '# Autostart the Dropbox deamon' >> ~/.config/openbox/autostart
+            echo "(sleep ${ans}s && ~/.dropbox-dist/dropboxd) &" >> ~/.config/openbox/autostart
+            echo >> ~/.config/openbox/autostart
         else
-            echo "" >> "/home/$USER/.config/openbox/autostart"
-            echo "# Autostart the Dropbox deamon" >> "/home/$USER/.config/openbox/autostart"
-            echo "~/.dropbox-dist/dropboxd &" >> "/home/$USER/.config/openbox/autostart"
-            echo "" >> "/home/$USER/.config/openbox/autostart"
+            echo >> ~/.config/openbox/autostart
+            echo '# Autostart the Dropbox deamon' >> ~/.config/openbox/autostart
+            echo '~/.dropbox-dist/dropboxd &' >> ~/.config/openbox/autostart
+            echo >> ~/.config/openbox/autostart
         fi
     fi
     zenity --question --title='Dropbox Installation' --text 'Do you wish to start the Dropbox client now?' || exit 0
@@ -111,8 +107,8 @@ if [[ ! -d $USERDBDIR ]]; then
     menuSeparator
     menuItem 'Find out more about Dropbox' 'x-www-browser http://db.tt/5mJg9lb'
 else
-    if [[ -d /home/$USER/Dropbox ]]; then
-        menuItem 'Open Dropbox Folder' 'thunar /home/$USER/Dropbox'
+    if [[ -d ~/Dropbox ]]; then
+        menuItem 'Open Dropbox Folder' 'thunar $HOME/Dropbox'
     fi
     if ! pidof dropbox > /dev/null; then
         menuItem 'Start Dropbox' 'cb-dropbox-pipemenu --start-dropbox'
diff --git a/cb-libreoffice-pipemenu b/cb-libreoffice-pipemenu
--- a/cb-libreoffice-pipemenu
+++ b/cb-libreoffice-pipemenu
@@ -5,12 +5,8 @@
 # by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
 # ---------------------------------------------------------------------
 
-pathto=$(readlink -f "$0" | sed 's%/*[^/]\+/*$%%')
-
-if [[ -f $pathto/cb-include.cfg ]]; then # but what for?
-    source "$pathto/cb-include.cfg"
-else
-    echo '  Failed to locate cb-include.cfg'
+if ! . cb-include.cfg &> /dev/null; then
+    echo '  Failed to locate cb-include.cfg in PATH' >&2
     exit 1
 fi
 
@@ -53,38 +49,18 @@ if [[ $1 = '--install-lo' ]]; then
     fi
     exit 0
 fi
+
 # Start pipemenu
 menuStart
 
-# Writer
-if [[ -x /usr/bin/lowriter ]]; then
-    INSTALLED=true
-    menuItem 'Writer' 'lowriter'
-fi
+tools=( 'writer' 'calc' 'impress' 'draw' 'base' )
 
-# Calc
-if [[ -x /usr/bin/localc ]]; then
-    INSTALLED=true
-    menuItem 'Calc' 'localc'
-fi
-
-# Impress
-if [[ -x /usr/bin/loimpress ]]; then
-    INSTALLED=true
-    menuItem 'Impress' 'loimpress'
-fi
-
-# Draw
-if [[ -x /usr/bin/lodraw ]]; then
-    INSTALLED=true
-    menuItem 'Draw' 'lodraw'
-fi
-
-# Base
-if [[ -x /usr/bin/lobase ]]; then
-    INSTALLED=true
-    menuItem 'Base' 'lobase'
-fi
+for curTool in "${tools[@]}"; do
+    if [[ -x /usr/bin/lo$curTool ]]; then
+        INSTALLED=true
+        menuItem "${curTool^}" "lo$curTool"
+    fi
+done
 
 if [[ ! $INSTALLED ]]; then
     menuItem 'Install LibreOffice' 'cb-libreoffice-pipemenu --install'
diff --git a/cb-printing-pipemenu b/cb-printing-pipemenu
--- a/cb-printing-pipemenu
+++ b/cb-printing-pipemenu
@@ -5,12 +5,8 @@
 # by Philip Newborough (aka corenominal) <mail@philipnewborough.co.uk>
 # ---------------------------------------------------------------------
 
-pathto=$(readlink -f "$0" | sed 's%/*[^/]\+/*$%%')
-
-if [[ -f $pathto/cb-include.cfg ]]; then
-    source "$pathto/cb-include.cfg"
-else
-    echo '  Failed to locate cb-include.cfg'
+if ! . cb-include.cfg &> /dev/null; then
+    echo '  Failed to locate cb-include.cfg in PATH' >&2
     exit 1
 fi
 
@@ -43,7 +39,6 @@ if [[ $1 = '--install-printing' ]]; then
             else
                 cb-printing-pipemenu --install-printing
             fi
-            exit 0
         else
             clear
             echo
@@ -51,12 +46,11 @@ if [[ $1 = '--install-printing' ]]; then
             echo
             echo '  Hit any key to exit...'
             read -n1 a
-            exit 0
         fi
-    else
-        exit 0
     fi
+    exit 0
 fi
+
 # Start pipemenu
 menuStart
 
@@ -69,4 +63,5 @@ fi
 
 # End pipemenu
 menuEnd
+
 exit 0
diff --git a/cb-remote-desktop-pipemenu b/cb-remote-desktop-pipemenu
--- a/cb-remote-desktop-pipemenu
+++ b/cb-remote-desktop-pipemenu
@@ -4,17 +4,10 @@
 # by Philip Newborough (aka corenominal) <corenominal@corenominal.org>
 # ---------------------------------------------------------------------
 
-pathto=$(readlink -f "$0" | sed 's%/*[^/]\+/*$%%')
-
-if [[ -f $pathto/cb-include.cfg ]]
-then
-    source "$pathto/cb-include.cfg"
-else
-    echo '  Failed to locate cb-include.cfg'
+if ! . cb-include.cfg &> /dev/null; then
+    echo '  Failed to locate cb-include.cfg in PATH' >&2
     exit 1
 fi
-
-I=0
 
 if [[ $1 = '--viewer' ]]; then
     terminator --title='Install VNC Viewer' --command='cb-remote-desktop-pipemenu --install-viewer'
@@ -33,10 +26,7 @@ if [[ $1 = '--install-viewer' ]]; then
     echo '  -----------------------------'
     echo '  This script will install TightVNC Viewer.'
     echo
-    echo -n '  Run the installer now? (Y|n) > '
-    read a
-    if [[ ${a,} = "y" || ! $a ]]; then
-        
+    if prompt '  Run the installer now?'; then
         connectiontest
         
         #update sources
@@ -45,20 +35,16 @@ if [[ $1 = '--install-viewer' ]]; then
 		sudo apt-get update
 		clear
         
-        
         if ! sudo apt-get install -y xtightvncviewer; then
             clear
             echo
             echo '  There was a problem installing TightVNC viewer.'
             echo
-            echo '  Hit any key to try again, or "q" to quit...'
-            read -n1 a
-            if [[ ${a,} = 'q' ]]; then
+            if prompt '  Hit any key to try again, or "q" to quit...' Q; then
                 clear
             else
                 cb-remote-desktop-pipemenu --install-viewer
             fi
-            exit 0
         else
             clear
             echo
@@ -66,7 +52,6 @@ if [[ $1 = '--install-viewer' ]]; then
             echo
             echo '  Hit any key to exit...'
             read -n1 a
-            exit 0
         fi
     fi
     exit 0
@@ -79,10 +64,7 @@ if [[ $1 = '--install-server' ]]; then
     echo '  -----------------------------'
     echo '  This script will install Vino VNC server.'
     echo
-    echo -n '  Run the installer now? (Y|n) > '
-    read a
-    if [[ ${a,} = 'y' || ! $a ]]; then
-        
+    if prompt '  Run the installer now?'; then
         connectiontest
         
         #update sources
@@ -91,20 +73,16 @@ if [[ $1 = '--install-server' ]]; then
 		sudo apt-get update
 		clear
         
-        
         if ! sudo apt-get install -y vino; then
             clear
             echo
             echo '  There was a problem installing Vino VNC server.'
             echo
-            echo '  Hit any key to try again, or "q" to quit...'
-            read -n1 a
-            if [[ ${a,} = "q" ]]; then
+            if prompt '  Hit any key to try again, or "q" to quit...' Q; then
                 clear
             else
                 cb-remote-desktop-pipemenu --install-server
             fi
-            exit 0
         else
             clear
             echo
@@ -112,7 +90,6 @@ if [[ $1 = '--install-server' ]]; then
             echo
             echo '  Hit any key to exit...'
             read -n1 a
-            exit 0
         fi
     fi
     exit 0
@@ -122,7 +99,7 @@ fi
 menuStart
 
 # Viewer
-if [[ -x /usr/bin/xtightvncviewer ]];then
+if [[ -x /usr/bin/xtightvncviewer ]]; then
     menuItem 'Viewer' 'vncviewer'
 else
     menuItem 'Install Viewer' 'cb-remote-desktop-pipemenu --viewer'
@@ -141,5 +118,7 @@ if [[ -x /usr/lib/vino/vino-server ]]; then
 else
     menuItem 'Install VNC Server' 'cb-remote-desktop-pipemenu --server'
 fi
+
 menuEnd
+
 exit 0
diff --git a/cb-x-www-browser-pipemenu b/cb-x-www-browser-pipemenu
--- a/cb-x-www-browser-pipemenu
+++ b/cb-x-www-browser-pipemenu
@@ -4,13 +4,8 @@
 # by Philip Newborough (aka corenominal) <corenominal@corenominal.org>
 # ---------------------------------------------------------------------
 
-pathto=$(readlink -f "$0" | sed 's%/*[^/]\+/*$%%')
-
-if [[ -f $pathto/cb-include.cfg ]]
-then
-    source "$pathto/cb-include.cfg"
-else
-    echo '  Failed to locate cb-include.cfg'
+if ! . cb-include.cfg &> /dev/null; then
+    echo '  Failed to locate cb-include.cfg in PATH' >&2
     exit 1
 fi
 
@@ -18,7 +13,6 @@ google_key_url_1='https://dl-ssl.google.com/linux/linux_signing_key.pub'
 google_key_url_2='http://packages.crunchbang.org/waldorf-files/apt-keys/google-chrome.key'
 opera_key_url_1='http://deb.opera.com/archive.key'
 opera_key_url_2='http://packages.crunchbang.org/waldorf-files/apt-keys/opera.key'
-I=0
 
 if [[ $1 =~ ^--(chromium-browser|iceweasel|google-chrome|opera)$ ]]; then
     browserName=${1:2}
@@ -27,7 +21,7 @@ if [[ $1 =~ ^--(chromium-browser|iceweasel|google-chrome|opera)$ ]]; then
     exit 0
 fi
 
-if [ "$1" = "--install-chromium-browser" ]; then
+if [[ $1 = '--install-chromium-browser'  ]]; then
     clear
     echo
     echo '  INSTALL CHROMIUM BROWSER'
@@ -52,7 +46,6 @@ if [ "$1" = "--install-chromium-browser" ]; then
             else
                 cb-x-www-browser-pipemenu --install-chromium-browser
             fi
-            exit 0
         else
             clear
             echo
@@ -60,14 +53,12 @@ if [ "$1" = "--install-chromium-browser" ]; then
             echo
             echo '  Hit any key to exit...'
             read -n1 a
-            exit 0
         fi
-    else
-        exit 0
     fi
+    exit 0
 fi
 
-if [ "$1" = "--install-iceweasel" ]; then
+if [[ $1 = '--install-iceweasel' ]]; then
     clear
     echo
     echo '  INSTALL ICEWEASEL BROWSER'
@@ -92,7 +83,6 @@ if [ "$1" = "--install-iceweasel" ]; then
             else
                 cb-x-www-browser-pipemenu --install-iceweasel
             fi
-            exit 0
         else
             clear
             echo
@@ -100,14 +90,12 @@ if [ "$1" = "--install-iceweasel" ]; then
             echo
             echo '  Hit any key to exit...'
             read -n1 a
-            exit 0
         fi
-    else
-        exit 0
     fi
+    exit 0
 fi
 
-if [ "$1" = "--install-google-chrome" ]; then
+if [[ $1 = '--install-google-chrome' ]]; then
     clear
     echo
     echo '  INSTALL GOOGLE CHROME WWW BROWSER'
@@ -121,11 +109,9 @@ if [ "$1" = "--install-google-chrome" ]; then
         clear
         echo '  Adding APT key...'
         sleep 2s
-        if ! wget -O google.key ${google_key_url_1} 2> /dev/null
-        then
+        if ! wget -O google.key "$google_key_url_1" 2> /dev/null; then
             # Fallback to packages.crunchbang.org.
-            if ! wget -O google.key ${google_key_url_2} 2> /dev/null
-            then
+            if ! wget -O google.key "$google_key_url_2" 2> /dev/null; then
                 echo '  Failed to retrieve APT key from Google Inc.'
                 clear
                 exit 1
@@ -137,7 +123,7 @@ if [ "$1" = "--install-google-chrome" ]; then
         #create sources file
         echo '  Creating APT sources file...'
         sleep 2s
-        if [ -f "/etc/apt/sources.list.d/google-chrome.list" ]; then
+        if [[ -f /etc/apt/sources.list.d/google-chrome.list ]]; then
             sudo rm -f '/etc/apt/sources.list.d/google-chrome.list'
         fi
         echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee -a '/etc/apt/sources.list.d/google-chrome.list'
@@ -158,7 +144,6 @@ if [ "$1" = "--install-google-chrome" ]; then
             else
                 cb-x-www-browser-pipemenu --install-google-chrome
             fi
-            exit 0
         else
             clear
             echo
@@ -166,14 +151,12 @@ if [ "$1" = "--install-google-chrome" ]; then
             echo
             echo '  Hit any key to exit...'
             read -n1 a
-            exit 0
         fi
-    else
-        exit 0
     fi
+    exit 0
 fi
 
-if [ "$1" = "--install-opera" ]; then
+if [[ $1 = '--install-opera' ]]; then
     clear
     echo
     echo '  INSTALL OPERA WWW BROWSER'
@@ -187,11 +170,9 @@ if [ "$1" = "--install-opera" ]; then
         clear
         echo '  Adding APT key...'
         sleep 2s
-        if ! wget -O opera.key ${opera_key_url_1} 2> /dev/null
-        then
+        if ! wget -O opera.key "$opera_key_url_1" 2> /dev/null; then
             # Fallback to packages.crunchbang.org.
-            if ! wget -O opera.key ${opera_key_url_2} 2> /dev/null
-            then
+            if ! wget -O opera.key "$opera_key_url_2" 2> /dev/null; then
                 echo '  Failed to retrieve APT key from Opera Software ASA.'
                 clear
                 exit 1
@@ -213,7 +194,6 @@ if [ "$1" = "--install-opera" ]; then
 		sudo apt-get update
 		clear
         
-        
         if ! sudo apt-get install -y opera; then
             clear
             echo
@@ -224,7 +204,6 @@ if [ "$1" = "--install-opera" ]; then
             else
                 cb-x-www-browser-pipemenu --install-opera
             fi
-            exit 0
         else
             clear
             echo
@@ -232,51 +211,30 @@ if [ "$1" = "--install-opera" ]; then
             echo
             echo '  Hit any key to exit...'
             read -n1 a
-            exit 0
         fi
-    else
-        exit 0
     fi
+    exit 0
 fi
+
 # Start pipemenu
 menuStart
 
-# Chromium
-if [[ -x /usr/bin/chromium-browser ]]; then
-    ((I++))
-    menuItem 'Chromium Browser' 'chromium-browser'
-    menuItem 'Chromium Browser (Private Mode)' 'chromium-browser --incognito'
-else
-    menuItem 'Install Chromium Browser' 'cb-x-www-browser-pipemenu --chromium-browser'
-fi
+tools=( 'chromium-browser' 'iceweasel' 'google-chrome' 'opera' )
 
-# Iceweasel
-if [[ -x /usr/bin/iceweasel ]]; then
-    ((I++))
-    menuItem 'Iceweasel' 'iceweasel'
-else
-    menuItem 'Install Iceweasel' 'cb-x-www-browser-pipemenu --iceweasel'
-fi
-
-# Google Chrome
-if [[ -x /usr/bin/google-chrome ]]; then
-    ((I++))
-    menuItem 'Google Chrome' 'google-chrome'
-    menuItem 'Google Chrome (Private Mode)' 'google-chrome --incognito'
-else
-    menuItem 'Install Google Chrome' 'cb-x-www-browser-pipemenu --google-chrome'
-fi
-
-# Opera
-if [[ -x /usr/bin/opera ]]; then
-    ((I++))
-    menuItem 'Opera' 'opera'
-else
-    menuItem 'Install Opera' 'cb-x-www-browser-pipemenu --opera'
-fi
+for curTool in "${tools[@]}"; do
+    curToolName=${curTool//-/ }
+    curToolName=${curToolName~}
+    if [[ -x /usr/bin/$curTool ]]; then
+        INSTALLED=true
+        menuItem "$curToolName" "$curTool"
+        [[ $curToolName =~ 'Chrom' ]] && menuItem "$curToolName (Private Mode)" "$curTool --incognito"
+    else
+        menuItem "Install $curToolName" "cb-x-www-browser-pipemenu --$curTool"
+    fi
+done
 
 # Configure default
-if (( I > 1 )); then
+if [[ $INSTALLED ]]; then
     menuSeparator
     menuItem 'Select default browser' 'terminator --command="sudo update-alternatives --config x-www-browser"'
 fi
