Updated references to scriptname in comments, and two minor tweaks.
Updated references to recently_opened_menu.sh to cb-recent-files-menu.
Outputs error message in menu if recently-used.xbel cannot be found.
Escape _ to __ in menu labels.

diff --git a/cb-recent-files-pipemenu b/cb-recent-files-pipemenu
--- a/cb-recent-files-pipemenu
+++ b/cb-recent-files-pipemenu
@@ -1,5 +1,5 @@
 #!/bin/sh
-#    recently_opened_menu.sh - a script to parse .recently-used.xbel
+#    cb-recent-files-pipemenu - a script to parse .recently-used.xbel
 #    and generate openbox pipe menu
 #    Copyright (C) 2010  John Crawley
 #
@@ -12,11 +12,11 @@
 #    but WITHOUT ANY WARRANTY; without even the implied warranty of
 #    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #    GNU General Public License for more details.
-#    version 2011/06/02
+#    version 2012/07/01-cb
 
 # Usage: add
-# <menu id="recent" label="Recent Files" execute="/path/to/recently_opened_menu.sh" />
-# to your .config/openbox/menu.xml, or use with dash_places_menu.sh (see comments there)
+# <menu id="recent" label="Recent Files" execute="/path/to/cb-recent-files-pipemenu" />
+# to your .config/openbox/menu.xml, or use with cb-places-pipemenu (see comments there)
 
 maximum_entries=15 # max. number of entries in menu
 
@@ -33,8 +33,11 @@ elif [ -r "${HOME}/.recently-used.xbel" ]
 then
     file_path="${HOME}/.recently-used.xbel"
 else
-    echo "$0: cannot find a readable recently-used.xbel file" >&2
-    exit 1
+	echo "$0: cannot find a readable recently-used.xbel file" >&2
+	echo '<openbox_pipe_menu>
+<separator label="No recently-used.xbel file found." />
+</openbox_pipe_menu>'
+	exit 1
 fi
 
 # if argument is --clear, empty .recently-used.xbel
@@ -57,7 +60,7 @@ mid='">
     <action name="Execute"><command>'
 post='</command></action>
     </item>'
-    
+
 files=$( tac "${file_path}" |  awk -v MAX="$maximum_entries" -v PR="$pre" -v MI="$mid" -v PO="$post" 'BEGIN {
     RS="</bookmark>";
     FS="<info>";
@@ -77,9 +80,10 @@ files=$( tac "${file_path}" |  awk -v MAX="$maximum_entries" -v PR="$pre" -v MI=
     gsub(/%3E/,"\\&gt;",$2)
     name=$2
     sub(/^.*\//,"",name)
+    gsub(/_/,"__",name)
     gsub(/\&apos;/,"\\&apos;\\&quot;\\&apos;\\&quot;\\&apos;",$2)
     print (PR name MI $1 " '"'"'" $2 "'"'"'" PO)
-}' )  
+}' )
 
 # use perl to decode urlencoded characters
 files=$(perl -MURI::Escape -e 'print uri_unescape($ARGV[0]);' "$files")
