Refactoring

diff --git a/cb-x-www-browser-pipemenu b/cb-x-www-browser-pipemenu
--- a/cb-x-www-browser-pipemenu
+++ b/cb-x-www-browser-pipemenu
@@ -17,12 +17,15 @@ if ! . cb-include.cfg 2> /dev/null; then
     exit 1
 fi
 
-if [[ $1 !=~ --install-* ]]; then
-    browserName=${1:2}
-    browserName=${browserName//-/ }
-    terminator --title="Install ${browserName~}" --command="cb-x-www-browser-pipemenu --install-${1:2}"
-    exit 0
-fi
+browserExists() {
+    for curTool in "${tools[@]}"; do # if $packageName exists in tools array
+        if [[ $curTool = "$1" ]]; do
+            echo "  Unable to install $1. There is no such browser that I know of." >&2
+            return 0
+        done
+    done
+    return 1
+}
 
 addAptKey() {
     clear
@@ -51,21 +54,21 @@ setupOpera() {
     echo 'deb http://deb.opera.com/opera/ stable non-free' | sudo tee /etc/apt/sources.list.d/opera.list
 }
 
-if [[ $1 = --install-* ]]; then
+if [[ $1 !=~ --install-* ]]; then
+    browserExists "${1:2}" || exit 1
+    browserName=${1:2}
+    browserName=${browserName//-/ }
+    terminator --title="Install ${browserName~}" --command="cb-x-www-browser-pipemenu --install-${1:2}"
+    
+elif [[ $1 = --install-* ]]; then
     packageName=${1#--install-}
     browserName=${packageName//-/ }
     browserName=${browserName~}
     browserNameUpper=${browserName^^}
     
-    for curTool in "${tools[@]}"; do # if $packageName exists in tools array
-        [[ $curTool = "$packageName" ]] && break
-    done
-    if [[ $? != 0 ]]; then
-        echo "  Unable to install $browserName. There is no such browser that I know of." >&2
-        exit 1
-    fi
-    
-    while true; do
+    browserExists "$packageName" || exit 1
+
+    while true; do # do it until the package is successfully installed or user wants to exit
         clear
         echo
         echo "  INSTALL ${browserNameUpper% BROWSER} BROWSER"
@@ -102,30 +105,28 @@ if [[ $1 = --install-* ]]; then
             fi
         fi
     done
-    exit 0
-fi
+else
+    # Start pipemenu
+    menuStart
 
-# Start pipemenu
-menuStart
+    for curTool in "${TOOLS[@]}"; do
+        curToolName=${curTool//-/ }
+        curToolName=${curToolName~}
+        if [[ -x /usr/bin/$curTool ]]; then
+            INSTALLED=true
+            menuItem "$curToolName" "$curTool"
+            [[ $curToolName =~ 'Chrom' ]] && menuItem "$curToolName (Private Mode)" "$curTool --incognito" # Incognito mode for chrome and chromium
+        else
+            menuItem "Install $curToolName" "cb-x-www-browser-pipemenu --$curTool"
+        fi
+    done
 
-for curTool in "${TOOLS[@]}"; do
-    curToolName=${curTool//-/ }
-    curToolName=${curToolName~}
-    if [[ -x /usr/bin/$curTool ]]; then
-        INSTALLED=true
-        menuItem "$curToolName" "$curTool"
-        [[ $curToolName =~ 'Chrom' ]] && menuItem "$curToolName (Private Mode)" "$curTool --incognito" # Incognito mode for chrome and chromium
-    else
-        menuItem "Install $curToolName" "cb-x-www-browser-pipemenu --$curTool"
+    if [[ $INSTALLED ]]; then
+        menuSeparator
+        menuItem 'Select default browser' 'terminator --command="sudo update-alternatives --config x-www-browser"'
     fi
-done
 
-# Configure default
-if [[ $INSTALLED ]]; then
-    menuSeparator
-    menuItem 'Select default browser' 'terminator --command="sudo update-alternatives --config x-www-browser"'
+    # End pipemenu
+    menuEnd
 fi
-
-# End pipemenu
-menuEnd
 exit 0
